name: logsheet_turbin
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  get: any
  shared_preferences: ^2.0.15
  flutter_spinkit: ^5.1.0
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  fl_chart: ^0.35.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/